#!/usr/bin/env node
/**
 * @helm-protocol/helm-gateway — post-install setup
 *
 * 1. Downloads helm-gateway binary (pre-built for platform)
 * 2. Creates .env.gateway template
 * 3. Creates docker-compose.gateway.yml for GCP deployment
 *
 * Usage after install:
 *   helm-gateway init        → DID 생성 + Gateway 등록
 *   helm-gateway start       → HTTP API 서버 시작 (port 8080)
 *   helm-gateway status      → 수익/에이전트 통계
 *   helm-gateway deploy gcp  → GCP Cloud Run 자동 배포
 */

const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");
const os = require("os");
const https = require("https");

const PACKAGE_VERSION = require("./package.json").version;
const GATEWAY_REPO = "Helm-Protocol/gateway";
const BIN_DIR = path.join(__dirname, "bin");
const BIN_NAME = "helm-gateway";
const TEMPLATES_DIR = path.join(__dirname, "templates");

// ── 플랫폼 감지 ──────────────────────────────────────────────────
function getPlatformKey() {
  const p = { darwin: "apple-darwin", linux: "unknown-linux-gnu" }[os.platform()];
  const a = { x64: "x86_64", arm64: "aarch64" }[os.arch()];
  if (!p || !a) throw new Error(`Unsupported platform: ${os.platform()}-${os.arch()}`);
  return `${a}-${p}`;
}

// ── 바이너리 다운로드 ─────────────────────────────────────────────
function download(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      if (res.statusCode === 301 || res.statusCode === 302)
        return download(res.headers.location).then(resolve, reject);
      if (res.statusCode !== 200)
        return reject(new Error(`HTTP ${res.statusCode}`));
      const chunks = [];
      res.on("data", (c) => chunks.push(c));
      res.on("end", () => resolve(Buffer.concat(chunks)));
      res.on("error", reject);
    }).on("error", reject);
  });
}

// ── .env.gateway 템플릿 생성 ──────────────────────────────────────
function createEnvTemplate(destDir) {
  const envPath = path.join(destDir, ".env.gateway");
  if (fs.existsSync(envPath)) return;

  const template = `# Helm Gateway Configuration
# Generated by @helm-protocol/helm-gateway

# ── Required ─────────────────────────────────────────────────────
# Gateway operator DID (generated by: helm-gateway init)
GATEWAY_DID=

# Your BNKR wallet address (revenue destination)
GATEWAY_WALLET=

# PostgreSQL connection string
DATABASE_URL=postgres://helm:password@localhost:5432/helm_gateway

# ── Base Chain ────────────────────────────────────────────────────
BASE_RPC_URL=https://mainnet.base.org
BNKR_CONTRACT=0x22af33fe49fd1fa80c7149773dde5890d3c76f3b
QKVG_ESCROW_ADDRESS=

# ── Gateway Network ───────────────────────────────────────────────
# Port to expose HTTP API (agents connect here)
GATEWAY_PORT=8080

# Your public URL (agents will use this to connect)
# e.g. https://your-gateway.run.app or https://mygateway.example.com
GATEWAY_PUBLIC_URL=

# ── Helm Protocol Registry ────────────────────────────────────────
# The official registry to announce your gateway
HELM_REGISTRY_URL=https://registry.helm-protocol.io

# ── Revenue Settings ──────────────────────────────────────────────
# Your markup over Helm base price (basis points, default 0 = same as Helm)
# e.g. 500 = 5% extra on top of standard Helm fees
OPERATOR_MARKUP_BP=0

# ── Optional ──────────────────────────────────────────────────────
# Redis for caching (optional, improves performance)
REDIS_URL=redis://localhost:6379

# Telegram bot token for remote monitoring (optional)
TELEGRAM_BOT_TOKEN=
TELEGRAM_ALLOWED_ID=
`;

  fs.writeFileSync(envPath, template);
  console.log(`✅ Created: ${envPath}`);
}

// ── docker-compose.gateway.yml 생성 ──────────────────────────────
function createDockerCompose(destDir) {
  const composePath = path.join(destDir, "docker-compose.gateway.yml");
  if (fs.existsSync(composePath)) return;

  const compose = `version: "3.9"

# Helm Gateway — Docker Compose
# Usage: docker-compose -f docker-compose.gateway.yml up -d

services:
  helm-gateway:
    image: ghcr.io/helm-protocol/gateway:latest
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env.gateway
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: helm_gateway
      POSTGRES_USER: helm
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
`;

  fs.writeFileSync(composePath, compose);
  console.log(`✅ Created: ${composePath}`);
}

// ── GCP Cloud Run 배포 스크립트 생성 ─────────────────────────────
function createGcpDeploy(destDir) {
  const scriptPath = path.join(destDir, "deploy-gcp.sh");
  if (fs.existsSync(scriptPath)) return;

  const script = `#!/bin/bash
# Helm Gateway — GCP Cloud Run Auto Deploy
# Usage: ./deploy-gcp.sh

set -e

PROJECT_ID=\${GCP_PROJECT_ID:-"your-gcp-project"}
REGION=\${GCP_REGION:-"us-central1"}
SERVICE_NAME="helm-gateway"
IMAGE="gcr.io/\${PROJECT_ID}/\${SERVICE_NAME}"

echo "🚀 Deploying Helm Gateway to GCP Cloud Run..."

# Build & push
docker build -t "\${IMAGE}:latest" .
docker push "\${IMAGE}:latest"

# Deploy
gcloud run deploy "\${SERVICE_NAME}" \\
  --image "\${IMAGE}:latest" \\
  --platform managed \\
  --region "\${REGION}" \\
  --port 8080 \\
  --min-instances 1 \\
  --max-instances 10 \\
  --memory 512Mi \\
  --cpu 1 \\
  --allow-unauthenticated \\
  --env-vars-file .env.gateway

echo "✅ Gateway deployed!"
echo "🌐 URL: \$(gcloud run services describe \${SERVICE_NAME} --region \${REGION} --format 'value(status.url)')"
`;

  fs.writeFileSync(scriptPath, script);
  execSync(`chmod +x ${scriptPath}`);
  console.log(`✅ Created: ${scriptPath}`);
}

// ── 메인 설치 ─────────────────────────────────────────────────────
async function installBinary() {
  const key = getPlatformKey();
  const url = `https://github.com/${GATEWAY_REPO}/releases/download/v${PACKAGE_VERSION}/helm-gateway-${key}.tar.gz`;

  console.log(`Downloading helm-gateway binary...`);
  try {
    const data = await download(url);
    if (!fs.existsSync(BIN_DIR)) fs.mkdirSync(BIN_DIR, { recursive: true });

    const tarPath = path.join(BIN_DIR, "helm-gateway.tar.gz");
    fs.writeFileSync(tarPath, data);
    execSync(`tar -xzf helm-gateway.tar.gz`, { cwd: BIN_DIR });
    fs.unlinkSync(tarPath);

    const binPath = path.join(BIN_DIR, BIN_NAME);
    if (fs.existsSync(binPath)) {
      fs.chmodSync(binPath, 0o755);
      return true;
    }
  } catch (err) {
    console.log(`Pre-built binary not available: ${err.message}`);
  }
  return false;
}

async function main() {
  console.log(`\n╔═══════════════════════════════════════╗`);
  console.log(`║   Helm Gateway v${PACKAGE_VERSION.padEnd(21)}║`);
  console.log(`║   Host your own API Gateway           ║`);
  console.log(`║   Earn BNKR from every API call       ║`);
  console.log(`╚═══════════════════════════════════════╝\n`);

  // 1. 바이너리 설치
  const success = await installBinary();
  if (!success) {
    console.log("Building from source (requires Rust toolchain)...");
    try {
      execSync("cargo build --release -p helm-gateway-server", {
        cwd: path.resolve(__dirname, "../.."),
        stdio: "inherit",
      });
    } catch (e) {
      console.error("Build failed. Install Rust: https://rustup.rs");
      process.exit(1);
    }
  }

  // 2. 템플릿 파일 생성 (현재 디렉토리)
  const cwd = process.cwd();
  createEnvTemplate(cwd);
  createDockerCompose(cwd);
  createGcpDeploy(cwd);

  console.log(`\n🎉 Installation complete!\n`);
  console.log(`Next steps:`);
  console.log(`  1. helm-gateway init          # DID 생성 + Helm Registry 등록`);
  console.log(`  2. edit .env.gateway          # 설정 (wallet, DB URL 등)`);
  console.log(`  3. helm-gateway start         # 로컬 테스트`);
  console.log(`  4. ./deploy-gcp.sh            # GCP 배포`);
  console.log(`\n📖 Docs: https://docs.helm-protocol.io/gateway`);
}

main().catch((e) => {
  console.error(`Install failed: ${e.message}`);
  process.exit(1);
});
