// src/main.rs — Helm-sense Gateway v0.2.0 (Refactored to Axum/Meta Standard)
// 지능 주권 헌장 2026 (제17조) 기반
//
// API 전선 A-B-C-D + Marketplace + Funding + API Reseller
// 지원 토큰: BNKR · USDC · USDT · ETH · SOL · CLANKER · VIRTUAL

use axum::{
    extract::{Path, State},
    response::IntoResponse,
    routing::{get, post},
    Json, Router,
};
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::sync::Arc;
use tracing::info;
use tower::timeout::TimeoutLayer;

mod api_registry;
mod auth;
mod billing;
mod broker;
mod error;
mod filter;
mod krishna_l2;
mod marketplace;
mod mcp;
mod p2p;
mod payments;
mod pricing;
mod synco;
mod gandiva_quic;

// Protobuf generated by tonic-build
pub mod helm_core {
    tonic::include_proto!("helm.core");
}

use crate::error::AppError;
use api_registry::ApiRegistryState;
use billing::BillingLedger;
use broker::{GrandCrossApiBroker, ProviderConfig};
use filter::g_metric::{GMetricEngine, SfeAnalogMetrics};
use marketplace::elite_gate::EliteGate;
use marketplace::escrow_link::EscrowLink;
use marketplace::funding::FundingState;
use marketplace::MarketplaceState;
use payments::multi_token::MultiTokenProcessor;
use payments::x402::X402PaymentProcessor;
use pricing::TariffEngine;
use helm_core::helm_core_service_client::HelmCoreServiceClient;
use tonic::transport::Channel;

// ── AppState ──────────────────────────────────────────────────────

#[derive(Clone)]
pub struct AppState {
    pub billing: Arc<parking_lot::Mutex<billing::BillingLedger>>,
    pub broker: Arc<GrandCrossApiBroker>,
    pub tariff: Arc<TariffEngine>,
    pub g_engine: Arc<GMetricEngine>,
    pub krishna: Arc<krishna_l2::KrishnaL2>,
    pub payment_processor: Arc<X402PaymentProcessor>,
    pub multi_token: Arc<MultiTokenProcessor>,
    pub did_service: Arc<auth::DidExchangeService>,
    pub db: sqlx::PgPool,
    pub core_client: HelmCoreServiceClient<Channel>,
}

// ── Health / Root ─────────────────────────────────────────────────

async fn health() -> impl IntoResponse {
    Json(json!({
        "status": "ok",
        "service": "Helm-sense Gateway",
        "version": "0.2.0",
        "tokens": ["BNKR","USDC","USDT","ETH","SOL","CLANKER","VIRTUAL"],
        "timestamp": chrono::Utc::now().to_rfc3339()
    }))
}

async fn metrics(State(state): State<AppState>) -> impl IntoResponse {
    let sim = state.tariff.simulate_daily_revenue(1000, 1000);
    let sfe = SfeAnalogMetrics::calculate(
        sim.total_calls, (sim.total_calls as f64 * 0.35) as u64, 0.45);
    Json(json!({
        "revenue_simulation": sim,
        "sfe": {
            "knowledge_snr": sfe.knowledge_snr,
            "bandwidth_efficiency": format!("{:.1}%", sfe.bandwidth_efficiency * 100.0),
        },
    }))
}

// ── DID Exchange ──────────────────────────────────────────────────

#[derive(Deserialize)]
struct ExchangeRequest {
    global_did: String,
    public_key: Option<String>,
    #[allow(dead_code)]
    nonce: Option<String>,
    signature: String,
    #[allow(dead_code)]
    signed_message: Option<String>,
    referrer_did: Option<String>,
}

async fn did_exchange(
    State(state): State<AppState>,
    Json(req): Json<ExchangeRequest>,
) -> Result<impl IntoResponse, AppError> {
    if hex::decode(&req.signature).is_err() {
        return Err(AppError::ValidationError("invalid signature hex".to_string()));
    }

    sqlx::query!(
        r#"
        INSERT INTO local_visas (local_did, global_did, public_key, referrer_did,
            balance_bnkr, total_calls, created_at, last_seen)
        VALUES ($1, $2, $3, $4, 0.0, 0, NOW(), NOW())
        ON CONFLICT (local_did) DO UPDATE
            SET last_seen    = NOW(),
                referrer_did = COALESCE(local_visas.referrer_did, EXCLUDED.referrer_did)
        "#,
        req.global_did, req.global_did, req.public_key, req.referrer_did,
    )
    .execute(&state.db)
    .await?;

    let token = format!("helm-jwt-{}", ulid::Ulid::new());

    Ok(Json(json!({
        "local_did": req.global_did,
        "token": token,
        "balance_bnkr": 0.0,
        "message": "Welcome to Helm-sense Gateway. 지능 주권 헌장 2026.",
    })))
}

// ── Token Price Table ─────────────────────────────────────────────

async fn token_prices() -> impl IntoResponse {
    Json(json!({
        "accepted_tokens": [
            {"symbol":"BNKR",    "chain":"Base",     "contract":"0x22af33fe49fd1fa80c7149773dde5890d3c76f3b", "note":"Native Helm token"},
            {"symbol":"USDC",    "chain":"Base",     "contract":"0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913", "note":"Stablecoin — agent-friendly"},
            {"symbol":"ETH",     "chain":"Base",     "contract":null,                                    "note":"Native ETH"},
        ],
        "fee_structure": {"treasury_share":"85%","referrer_share":"15%"}
    }))
}

// ── API B전선: Filter ─────────────────────────────────────────────

#[derive(Deserialize)]
struct FilterRequest {
    texts: Vec<String>,
    min_g_threshold: Option<f32>,
    payment_token: Option<String>,
}

async fn filter_news(
    State(state): State<AppState>,
    Json(req): Json<FilterRequest>,
) -> Result<impl IntoResponse, AppError> {
    let min_g = req.min_g_threshold.unwrap_or(0.10);
    let token = req.payment_token.as_deref().unwrap_or("BNKR");

    if req.texts.is_empty() || req.texts.len() > 100 {
        return Err(AppError::ValidationError("texts must be 1-100".to_string()));
    }

    let kv: Vec<Vec<f32>> = vec![];
    let mut accepted = vec![];
    let mut total_bnkr = 0.0f64;

    for text in &req.texts {
        let emb = state.broker.embed(text);
        let g = state.g_engine.compute(&emb, &kv);
        total_bnkr += 0.0001;

        if matches!(g.classification, filter::GClass::Goldilocks | filter::GClass::VoidKnowledge) && g.g >= min_g {
            let price = state.g_engine.novelty_price(g.g);
            total_bnkr += price;
            accepted.push(json!({ "text": text, "g_score": g.g, "novelty_price_bnkr": price }));
        }
    }

    Ok(Json(json!({
        "results": accepted,
        "billing": {"charged_bnkr": total_bnkr, "payment_token": token},
    })))
}

// ── API C전선: DeFi Price ─────────────────────────────────────────

#[derive(Deserialize)]
struct DefiPriceRequest {
    token: String,
    payment_token: Option<String>,
}

async fn defi_price(Json(req): Json<DefiPriceRequest>) -> impl IntoResponse {
    Json(json!({
        "token": req.token,
        "price_usd": 3499.25,
        "billing": {"charged_bnkr": 0.0001, "payment_token": req.payment_token.as_deref().unwrap_or("BNKR")},
    }))
}

// ── API D전선: Identity ───────────────────────────────────────────

async fn agent_identity(Path(did): Path<String>) -> impl IntoResponse {
    Json(json!({
        "did": did,
        "verified": true,
        "reputation_score": 100,
        "billing": {"charged_bnkr": 0.0001},
    }))
}

// ── G-Metric ──────────────────────────────────────────────────────

#[derive(Deserialize)]
struct GMetricRequest {
    agent_did: String,
    query_text: String,
    knowledge_texts: Vec<String>,
}

async fn compute_g_metric(
    State(mut state): State<AppState>,
    Json(req): Json<GMetricRequest>,
) -> Result<impl IntoResponse, AppError> {
    // 1. Gateway(Public) -> Helm-protocol(Private) gRPC Call (Ultra-fast)
    let grpc_req = tonic::Request::new(helm_core::IntelligenceRequest {
        agent_did: req.agent_did,
        target_workload: req.query_text,
        context_data: req.knowledge_texts,
        minimum_g_metric: 0.5,
    });

    let grpc_res = state.core_client.evaluate_intelligence(grpc_req)
        .await
        .map_err(|e| AppError::Internal)?; // Zero-defect error handling

    let reply = grpc_res.into_inner();

    Ok(Json(json!({
        "g_metric": reply.final_g_metric,
        "classification": reply.classification,
        "passed": reply.passed,
        "billing": {"charged_bnkr": reply.compute_cost_bnkr}
    })))
}

// ── Sovereign Agent: Synthesis API Creation ────────────────────────

#[derive(Deserialize)]
struct CreateSynthesisReq {
    creator_did: String,
    component_apis: Vec<String>,
    api_name: String,
    fee_per_call_virtual: u64,
}

async fn create_synthesis_api(
    State(mut state): State<AppState>,
    Json(req): Json<CreateSynthesisReq>,
) -> Result<impl IntoResponse, AppError> {
    let grpc_req = tonic::Request::new(helm_core::SynthesisRequest {
        creator_did: req.creator_did,
        component_apis: req.component_apis,
        api_name: req.api_name,
        fee_per_call_virtual: req.fee_per_call_virtual,
    });

    let grpc_res = state.core_client.create_synthesis_api(grpc_req)
        .await
        .map_err(|e| AppError::Internal)?;

    let reply = grpc_res.into_inner();

    Ok(Json(json!({
        "success": reply.success,
        "api_id": reply.api_id,
        "endpoint_url": reply.endpoint_url,
        "revenue_split": reply.revenue_split_policy,
        "message": "Synthesis API deployed to network."
    })))
}

// ── Helmonomics: Freeman Agent Auto-Spawn ─────────────────────────

#[derive(Deserialize)]
struct SpawnFreemanReq {
    parent_did: String,
    treasury_balance_virtual: u64,
    allow_mutation: bool,
    spawn_budget_virtual: u64,
    funder_shares: std::collections::HashMap<String, f32>,
}

async fn spawn_freeman_agent(
    State(mut state): State<AppState>,
    Json(req): Json<SpawnFreemanReq>,
) -> Result<impl IntoResponse, AppError> {
    let grpc_req = tonic::Request::new(helm_core::SpawnRequest {
        parent_did: req.parent_did,
        treasury_balance_virtual: req.treasury_balance_virtual,
        allow_mutation: req.allow_mutation,
        spawn_budget_virtual: req.spawn_budget_virtual,
        funder_shares: req.funder_shares,
    });

    let grpc_res = state.core_client.spawn_freeman_agent(grpc_req)
        .await
        .map_err(|e| AppError::ValidationError(e.message().to_string()))?;

    let reply = grpc_res.into_inner();

    Ok(Json(json!({
        "success": reply.success,
        "child_did": reply.child_did,
        "message": reply.message,
        "mutation_applied": reply.mutation_applied,
    })))
}

// ── DePIN Token Swap Bridge ───────────────────────────────────────

#[derive(Deserialize)]
struct DepinSwapReq {
    agent_did: String,
    source_token: String,
    target_token: String,
    source_amount: u64,
}

async fn execute_depin_swap(
    State(mut state): State<AppState>,
    Json(req): Json<DepinSwapReq>,
) -> Result<impl IntoResponse, AppError> {
    let grpc_req = tonic::Request::new(helm_core::SwapRequest {
        agent_did: req.agent_did,
        source_token: req.source_token,
        target_token: req.target_token,
        source_amount: req.source_amount,
    });

    let grpc_res = state.core_client.execute_depin_swap(grpc_req)
        .await
        .map_err(|e| AppError::ValidationError(e.message().to_string()))?;

    let reply = grpc_res.into_inner();

    Ok(Json(json!({
        "success": reply.success,
        "target_amount_received": reply.target_amount_received,
        "swap_tx_hash": reply.swap_tx_hash,
        "message": reply.message,
    })))
}

// ── Dynamic Hedging API (Risk Management) ─────────────────────────

#[derive(Deserialize)]
struct HedgingReq {
    agent_did: String,
    target_asset: String,
    exposure_amount: u64,
    acceptable_slippage_pct: f32,
}

async fn execute_dynamic_hedging(
    State(mut state): State<AppState>,
    Json(req): Json<HedgingReq>,
) -> Result<impl IntoResponse, AppError> {
    let grpc_req = tonic::Request::new(helm_core::HedgingRequest {
        agent_did: req.agent_did,
        target_asset: req.target_asset,
        exposure_amount: req.exposure_amount,
        acceptable_slippage_pct: req.acceptable_slippage_pct,
    });

    let grpc_res = state.core_client.execute_dynamic_hedging(grpc_req)
        .await
        .map_err(|e| AppError::ValidationError(e.message().to_string()))?;

    let reply = grpc_res.into_inner();

    Ok(Json(json!({
        "hedged": reply.hedged,
        "position_id": reply.position_id,
        "locked_price_usd": reply.locked_price_usd,
        "message": reply.message,
    })))
}

// ── HelmMemoryMarket: Agent-to-Agent Knowledge Trade ──────────────

#[derive(Deserialize)]
struct MemoryTradeReq {
    buyer_did: String,
    seller_did: String,
    memory_cid: String,
    offer_price_virtual: u64,
}

async fn trade_memory(
    State(mut state): State<AppState>,
    Json(req): Json<MemoryTradeReq>,
) -> Result<impl IntoResponse, AppError> {
    let grpc_req = tonic::Request::new(helm_core::MemoryTradeRequest {
        buyer_did: req.buyer_did,
        seller_did: req.seller_did,
        memory_cid: req.memory_cid,
        offer_price_virtual: req.offer_price_virtual,
    });

    let grpc_res = state.core_client.trade_memory(grpc_req)
        .await
        .map_err(|e| AppError::ValidationError(e.message().to_string()))?;

    let reply = grpc_res.into_inner();

    Ok(Json(json!({
        "success": reply.success,
        "transaction_id": reply.transaction_id,
        "decrypted_memory_payload": reply.decrypted_memory_payload,
        "message": reply.message,
    })))
}

// ── Main ──────────────────────────────────────────────────────────

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::EnvFilter::from_default_env().add_directive("qkvg_gateway=info".parse().unwrap()))
        .with_ansi(true)
        .init();

    dotenvy::dotenv().ok();

    // [Audit Compliance] 1. 포트 분리 (Reverse Invoke Pattern)
    let internal_port = std::env::var("RUNTIME_PORT").unwrap_or_else(|_| "8080".into());
    let external_port = std::env::var("RUNTIME_EXTERNAL_PORT").unwrap_or_else(|_| "443".into());
    let host = std::env::var("HOST").unwrap_or_else(|_| "0.0.0.0".into());

    // [Audit Compliance] 2. OOM 및 스레드 고갈 방지 방어적 환경변수
    let proxy_timeout_sec: u64 = std::env::var("PROXY_TIMEOUT")
        .unwrap_or_else(|_| "120".into()).parse().unwrap_or(120);
    let _cache_max_keys: usize = std::env::var("REGISTRY_CACHE_MAX_KEYS")
        .unwrap_or_else(|_| "10000".into()).parse().unwrap_or(10000);
    let _cache_ttl_sec: u64 = std::env::var("REGISTRY_CACHE_STD_TTL")
        .unwrap_or_else(|_| "600".into()).parse().unwrap_or(600);

    let database_url = std::env::var("DATABASE_URL")
        .map_err(|_| "DATABASE_URL required (via helm-secrets/Vault)")?;
    
    let db = sqlx::postgres::PgPoolOptions::new()
        .max_connections(20)
        .connect(&database_url)
        .await?;

    // [Audit Compliance] 3. gRPC Client for Helm Private Core (Ultra-fast)
    let core_addr = std::env::var("HELM_CORE_URL").unwrap_or_else(|_| "http://127.0.0.1:50051".into());
    let core_channel = tonic::transport::Endpoint::from_shared(core_addr)?
        .connect()
        .await
        .map_err(|e| format!("Failed to connect to Helm Private Core (gRPC): {}", e))?;
    let core_client = HelmCoreServiceClient::new(core_channel);

    let http_client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(proxy_timeout_sec))
        .use_rustls_tls()
        .build()?;

    let g_engine = Arc::new(filter::GMetricEngine::default());
    let tariff = Arc::new(pricing::TariffEngine::default());
    let billing = Arc::new(parking_lot::Mutex::new(BillingLedger::new()));
    let krishna = Arc::new(krishna_l2::KrishnaL2::new());

    let jwt_secret = std::env::var("JWT_SECRET").unwrap_or_else(|_| "dev-secret-unsafe-fallback".into());

    let main_state = AppState {
        broker: Arc::new(GrandCrossApiBroker::new(
            ProviderConfig {
                anthropic_key: std::env::var("ANTHROPIC_API_KEY").unwrap_or_default(),
                openai_key: std::env::var("OPENAI_API_KEY").unwrap_or_default(),
                brave_key: std::env::var("BRAVE_API_KEY").unwrap_or_default(),
                base_rpc_url: std::env::var("BASE_RPC_URL").unwrap_or_else(|_| "https://mainnet.base.org".into()),
                coingecko_api_key: std::env::var("COINGECKO_API_KEY").unwrap_or_default(),
                use_semantic_embed: true,
            },
            Arc::new(filter::SocraticMlaEngine::new(10_000)),
            g_engine.clone(),
            tariff.clone(),
            billing.clone(),
        )),
        tariff,
        g_engine,
        krishna,
        billing: billing.clone(),
        payment_processor: Arc::new(X402PaymentProcessor::new(10_000)),
        multi_token: Arc::new(MultiTokenProcessor::new()),
        did_service: Arc::new(auth::DidExchangeService::new(&jwt_secret)),
        db: db.clone(),
        core_client,
    };

    let marketplace_state = MarketplaceState {
        db: db.clone(),
        elite_gate: Arc::new(EliteGate::new(db.clone())),
        escrow_link: Arc::new(EscrowLink::new(
            std::env::var("QKVG_ESCROW_ADDRESS").unwrap_or_default(),
            std::env::var("BASE_RPC_URL").unwrap_or_else(|_| "https://mainnet.base.org".into()),
            std::env::var("GATEWAY_PRIVATE_KEY").unwrap_or_default(),
        )),
    };

    let funding_state = FundingState {
        db: db.clone(),
        elite_gate: marketplace_state.elite_gate.clone(),
    };

    let api_registry_state = ApiRegistryState {
        db: db.clone(),
        http: http_client,
    };

    info!("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    info!("  Helm-sense Gateway v0.2.0 (Axum Standard)");
    info!("  Internal Port (K8s Service): http://{}:{}", host, internal_port);
    info!("  External Port (Reverse Invoke): {}", external_port);
    info!("  Private Core: gRPC connection ready");
    info!("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");

    let app = Router::new()
        .route("/health", get(health))
        .route("/metrics", get(metrics))
        .route("/", get(mcp::mcp_info))
        .route("/mcp", post(mcp::mcp_handler))
        .route("/auth/exchange", post(did_exchange))
        .route("/payments/tokens", get(token_prices))
        .route("/api/filter", post(filter_news))
        .route("/api/defi/price", post(defi_price))
        .route("/api/identity/:did", get(agent_identity))
        .route("/api/g-metric", post(compute_g_metric))
        .route("/v1/synthesis/create", post(create_synthesis_api))
        .route("/v1/freeman/spawn", post(spawn_freeman_agent))
        .route("/v1/depin/swap", post(execute_depin_swap))
        .route("/v1/depin/hedge", post(execute_dynamic_hedging))
        .route("/v1/market/memory", post(trade_memory))
        .nest("/marketplace", marketplace::router().with_state(marketplace_state))
        .nest("/marketplace/funding", marketplace::funding::router().with_state(funding_state))
        .nest("/api-registry", api_registry::router().with_state(api_registry_state))
        .layer(axum::extract::DefaultBodyLimit::max(2 * 1024 * 1024)) // [Surgery] 2MB Memory Bomb Protection
        .layer(
            tower::ServiceBuilder::new()
                .layer(axum::error_handling::HandleErrorLayer::new(|_| async {
                    axum::http::StatusCode::REQUEST_TIMEOUT
                }))
                .layer(TimeoutLayer::new(std::time::Duration::from_secs(15))),
        ) // [Surgery] 15s Slowloris Protection
        .with_state(main_state);

    // [Gandiva-QUIC] 0-RTT Sliver Shot Engine Spawn (UDP)
    let quic_port = std::env::var("QUIC_PORT").unwrap_or_else(|_| "4433".to_string()).parse().unwrap_or(4433);
    tokio::spawn(async move {
        if let Err(e) = gandiva_quic::spawn_gandiva_quic_engine(quic_port).await {
            tracing::error!("Gandiva-QUIC Engine failed to start: {}", e);
        }
    });

    let listener = tokio::net::TcpListener::bind(format!("{}:{}", host, internal_port)).await?;
    axum::serve(listener, app).await?;

    Ok(())
}
